name: Infra Deploy

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: GithubRole
          role-skip-session-tagging: true
          aws-region: ${{ env.AWS_REGION }}